version: '3.9'

services:
  app:
    container_name: app
    build: ./hadoop/data
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./hadoop/data/output:/app/output

  hadoop:
    container_name: hadoop
    build: ./hadoop
    ports:
      - "50070:50070"
      - "8088:8088"
      - "9000:9000"
      - "50075:50075"
      - "50010:50010"
      - "50020:50020"
      - "50090:50090"
      - "8020:8020"
      - "9864:9864"
      - "9870:9870"
      - "10020:10020"
      - "19888:19888"
      - "8030:8030"
      - "8031:8031"
      - "8032:8032"
      - "8033:8033"
      - "8040:8040"
      - "8042:8042"
      - "22:22"
    restart: always
    depends_on:
      - app
    volumes:
      - ./hadoop/data/output:/home/hduser/data/output

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=tarea3
      - MONGO_INITDB_DATABASE=wiki

  cliente:
    container_name: cliente
    build: ./cliente
    ports:
      - "5000:5000"
    restart: always