version: '3.9'

services:
  hadoop:
    container_name: hadoop
    build: ./hadoop
    ports:
      - "50070:50070"
      - "8088:8088"
      - "9000:9000"
      - "50075:50075"
      - "50010:50010"
      - "50020:50020"
      - "50090:50090"
      - "8020:8020"
      - "9864:9864"
      - "9870:9870"
      - "10020:10020"
      - "19888:19888"
      - "8030:8030"
      - "8031:8031"
      - "8032:8032"
      - "8033:8033"
      - "8040:8040"
      - "8042:8042"
      - "22:22"
    restart: always
    volumes:
      - ./hadoop/output:/home/hduser/data/output

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tarea3
      - TZ=America/Santiago
    ports:
      - "5432:5432"
    restart: always

  cliente:
    container_name: cliente
    build: ./cliente
    ports:
      - "5000:5000"
    restart: always